### PR TITLE
Add Kotlin Kolkata User Group and book Reactive Programming in Kotlin

### PR DESCRIPTION
**Pull request by RivuChk**
I've committed to add Kotlin Kolkata User Group and my book Reactive Programming in Kotlin

### CODE REVIEW

**Comment by IRus** [comment]
Thanks. also I noticing you deleted and replaced some files in repository, so I fix this is https://github.com/KotlinBy/awesome-kotlin/commit/013a68de6c654ceac9482d39662a71f41f0c024e.

Do you know how it happens?

**Comment by RivuChk** [comment]
Not sure, maybe a merge conflict or something?

**Comment by IRus** [comment]
Looks like problem with `:` on your system: https://github.com/KotlinBy/awesome-kotlin/pull/238/commits/6b5b9b8d28c4a1fa911e867518bc1b1edcdd7e61

**Comment by RivuChk** [comment]
Yeah, looks like that. I'll check, thanks for pointing.

**Comment by IRus** [comment]
Maybe you can say what is you system? (version/filesystem)

**Comment by RivuChk** [comment]
OS - Windows 10 (64 bit), Filesystem - NTFS, Used Application to edit - Notepad++

**Comment by IRus** [comment]
Thanks, I'll check checkout/commit to repo on win10. I think that there are problem with NTFS, I'm linux user, so I doesn't know about such problems.

**Pull request merged**
