### PR TITLE
Refresh of graphics ecosystem libraries plus two OpenGL tutorials

### PR DESCRIPTION
**Pull request by elect86**
As titled :)

### CODE REVIEW

**Comment by IRus** [comment]
Wow! Thanks a lot for your job and contribution :)

**Comment by elect86** [comment]
Thanks you for this awesome project! B-)

**Comment by elect86** [comment]
Ps: I was thinking, what about moving `kotlin-unsigned` from Misc to Graphics? Does it make sense to you?

**Comment by IRus** [comment]
Yep, it's better place than misc

**Pull request merged**
