### PR TITLE
Feature/GitHub actions

### PR DESCRIPTION
**Pull request by IRus**

### CODE REVIEW

**Comment by IRus** [comment]
How to build PR but not push?
Upload-download artifact between jobs, ugh

**Comment by madhead** [comment]
>How to build PR but not push?
Instead of separating PRs from non-PRs you could separate pushes to main branch from other pushes. Pushing to other brances than the main branch almost always means a PR:

```
on:
  push:
    branches-ignore:
      - main
```

Pushes to main branch almost always means merges (unless you're pushing directly to main):

```
on:
  push:
    branches:
      - main
```

Doing so will run pipelines only ones for a single SHA-1, while doing this:

```yml
on:
  - push
``` 

You can also target a PR specifically, probably with a branch:

```yml
on:
  pull_request:
    branches:
      - master
```

However remember that `on` clauses are evaluated independently for each workflows, so more that one workflow could be triggered for any commit / push.

**Comment by IRus** [comment]
So I can create **build** workflow for `on: push`, but I also want to deploy **on push branch main**. That means I have to create a separate workflow where I pretty much copy-paste **build** workflow job + introduce **build-and-push-image** job. Can I share **build** job between workflows? Or I'm missing the obvious way to do it right without code duplication?

> works between jobs of a single workflow

Right, I wonder why it's needed at all, and jobs didn't share file system state :(

**Comment by IRus** [comment]
Looks like my issue can be solved by `job.if` https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#determining-when-to-use-contexts

**Comment by IRus** [comment]
Disappointed with GitHub Actions, GitHub integration (tokens, UI) is great, but resulting workflows kinda ugly

**Comment by madhead** [comment]
Well, it's probably a matter of a habbit or mindset. I understand what you're talking about (in Java world usual build is ~ `gradle check` and release is ~ `gradle assemble` everything other is the same, so hence the copy-pasting problem). But..

What you can do instead is invent a way to inter-communicate between workflows based on the list of event triggers. E.g. to get rid of build phase in your deploy workflow you could probably pubish build artifacts to GitHub Packages, and then, on release workflow, just get those pre-build packages and use them for deployement. I tried that [here](https://github.com/madhead/ImgMacroBot):
- The deploy workflow [uses](https://github.com/madhead/ImgMacroBot/blob/master/.github/workflows/deploy.yml) a GH release
- GH release [is published](https://github.com/madhead/ImgMacroBot/blob/master/.github/workflows/master.yml) by pushes to master.
- Deploy workflows doesn't have any biuld logic.
- Communication is via workflow events

**Comment by IRus** [comment]
Right, in your example you run `gradlew test` for PR/push and `gradlew assemble` only for master branch. So not much duplication (no caches to speedup build either). In this repo case `build` step kinda big itself (and I even didn't add yarn cache yet), and copy-pasting it between jobs in meh moment

Thank you for your help btw :)

**Comment by madhead** [comment]
>Right, I wonder why it's needed at all, and jobs didn't share file system state :(

Well, a surprising fact about the jobs is that they run in parallel as well. That's why they don't share an FS by default. However, you can make them run one after another by establishing dependencies. There is now way to establish dependencies between workflows, however, other then by triggering events (e.g. one workflow makes a release and the other workflow is triggered by a that release). The most flexible way could be `repository_dispatch` event which is basically a JSON with arbitrary payload.

Artifacts could be helpful for build logs and test results. A surprising fact about them is that they don't overwrite each other, but append. E.g. if one of your jobs (named `first`) creates an artifact with a name `artifact` and uploads `./first` directory there, and other job (`second`) creates the same artifact named `artifact` and uploads directory `./second` there and then you download this artifact after both jobs are finished (parallel or sequential doesn't matter) - the resulting artifact will contain both directories. Syntetic example could be found [here](https://github.com/madhead/github-actions-demo/blob/master/.github/workflows/default.yml).

However, my understanding of the artifacts is that they don't provide a good way to share data for build / test / release / deploy phases and it's better to use external artifactory + events.

**Pull request merged**
